name: "infra preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - 10_infra/**   

permissions:
  id-token: write
  contents: read

env: 
  TF_VERSION: 1.1.7

defaults:
  run:
    shell: bash
    working-directory: "10_infra/"

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps: 
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Setup terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: ${{ env.TF_VERSION }}

